<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Demo Suite" duration-ms="40970" started-at="2019-04-10T12:41:57Z" finished-at="2019-04-10T12:42:38Z">
    <groups>
    </groups>
    <test name="Demo Test" duration-ms="40970" started-at="2019-04-10T12:41:57Z" finished-at="2019-04-10T12:42:38Z">
      <class name="testCasess.Demo">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:testCasess.Demo@4f18837a]" name="beforeTest" is-config="true" duration-ms="3110" started-at="2019-04-10T12:41:57Z" finished-at="2019-04-10T12:42:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="demo(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testCasess.Demo@4f18837a]" name="demo" duration-ms="36689" started-at="2019-04-10T12:42:00Z" finished-at="2019-04-10T12:42:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Vilmantas]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Kirda]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Europe]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[WebElement Commands]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Automation Practice Form]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[Automation Practice Table]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[C:\\Users\\Vilmis\\Downloads]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at testCasess.Demo.demo(Demo.java:119)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demo -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:testCasess.Demo@4f18837a]" name="afterMethod" is-config="true" duration-ms="456" started-at="2019-04-10T12:42:37Z" finished-at="2019-04-10T12:42:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=demo status=FAILURE method=Demo.demo(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testCasess.Demo@4f18837a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testCasess.Demo@4f18837a]" name="afterTest" is-config="true" duration-ms="689" started-at="2019-04-10T12:42:37Z" finished-at="2019-04-10T12:42:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- testCasess.Demo -->
    </test> <!-- Demo Test -->
  </suite> <!-- Demo Suite -->
</testng-results>
